<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Location', 'doctrine');

/**
 * BaseLocation
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $city_part
 * @property string $city
 * @property Doctrine_Collection $Property
 * 
 * @method integer             getId()        Returns the current record's "id" value
 * @method string              getCityPart()  Returns the current record's "city_part" value
 * @method string              getCity()      Returns the current record's "city" value
 * @method Doctrine_Collection getProperty()  Returns the current record's "Property" collection
 * @method Location            setId()        Sets the current record's "id" value
 * @method Location            setCityPart()  Sets the current record's "city_part" value
 * @method Location            setCity()      Sets the current record's "city" value
 * @method Location            setProperty()  Sets the current record's "Property" collection
 * 
 * @package    RentAFlat
 * @subpackage model
 * @author     Serge Frézier  with NetBeans IDE 8.2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseLocation extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('location');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('city_part', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => false,
             'autoincrement' => false,
             'length' => '',
             ));
        $this->hasColumn('city', 'string', null, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => '',
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Property', array(
             'local' => 'id',
             'foreign' => 'location_id'));
    }
}