<?php
// Connection Component Binding
Doctrine_Manager::getInstance()->bindComponent('Disposition', 'doctrine');

/**
 * BaseDisposition
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @property integer $id
 * @property string $text
 * @property Doctrine_Collection $Property
 * 
 * @method integer             getId()       Returns the current record's "id" value
 * @method string              getText()     Returns the current record's "text" value
 * @method Doctrine_Collection getProperty() Returns the current record's "Property" collection
 * @method Disposition         setId()       Sets the current record's "id" value
 * @method Disposition         setText()     Sets the current record's "text" value
 * @method Disposition         setProperty() Sets the current record's "Property" collection
 * 
 * @package    RentAFlat
 * @subpackage model
 * @author     Serge Frézier  with NetBeans IDE 8.2
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
abstract class BaseDisposition extends sfDoctrineRecord
{
    public function setTableDefinition()
    {
        $this->setTableName('disposition');
        $this->hasColumn('id', 'integer', 4, array(
             'type' => 'integer',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => true,
             'autoincrement' => true,
             'length' => 4,
             ));
        $this->hasColumn('text', 'string', 255, array(
             'type' => 'string',
             'fixed' => 0,
             'unsigned' => false,
             'primary' => false,
             'notnull' => true,
             'autoincrement' => false,
             'length' => 255,
             ));

        $this->option('type', 'INNODB');
        $this->option('collate', 'utf8_general_ci');
        $this->option('charset', 'utf8');
    }

    public function setUp()
    {
        parent::setUp();
        $this->hasMany('Property', array(
             'local' => 'id',
             'foreign' => 'disposition_id'));
    }
}