<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2017/02/21 01:37:15

return array(
'doctrine' => new sfDoctrineDatabase(array (
  'dsn' => 'mysql:host=127.0.0.1:3306;dbname=rentaflat;charset=utf8',
  'username' => 'root',
  'password' => NULL,
  'name' => 'doctrine',
)),);
