<?php

/**
 * DispositionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class DispositionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object DispositionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Disposition');
    }
}