<?php

/**
 * PropertyTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PropertyTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PropertyTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('Property');
    }
}