<?php

/**
 * PropertyBuildTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class PropertyBuildTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object PropertyBuildTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('PropertyBuild');
    }
}